PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE vocab (
    word TEXT NOT NULL,
    translation TEXT,
    article TEXT,
    praeteritum TEXT,
    perfekt TEXT,
    plural_form TEXT,
    page INTEGER NOT NULL CHECK (page BETWEEN 1 AND 6)
);
INSERT INTO vocab VALUES('Herkunft','origin; background','die',NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Motiv','motive; reason; motif','das',NULL,NULL,'Motive',1);
INSERT INTO vocab VALUES('entwerfen','to design; to draft',NULL,'entwarf','hat entworfen',NULL,1);
INSERT INTO vocab VALUES('kommentieren','to comment on',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Alternative','alternative','die',NULL,NULL,'Alternativen',1);
INSERT INTO vocab VALUES('Aufzählung','enumeration; listing','die',NULL,NULL,'Aufzählungen',1);
INSERT INTO vocab VALUES('Einschränkung','restriction; limitation','die',NULL,NULL,'Einschränkungen',1);
INSERT INTO vocab VALUES('Gegensatz','opposite; contrast','der',NULL,NULL,'Gegensätze',1);
INSERT INTO vocab VALUES('Geschmack','taste','der',NULL,NULL,'Geschmäcker',1);
INSERT INTO vocab VALUES('denselben Geschmack haben','to have the same taste',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Missverständnis','misunderstanding','das',NULL,NULL,'Missverständnisse',1);
INSERT INTO vocab VALUES('Neuigkeit','news; novelty','die',NULL,NULL,'Neuigkeiten',1);
INSERT INTO vocab VALUES('Neuigkeiten austauschen','to exchange news',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Umfrage','survey; poll','die',NULL,NULL,'Umfragen',1);
INSERT INTO vocab VALUES('anvertrauen','to entrust',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('jemandem etwas ausmachen','to matter to someone; to bother someone',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('bezeichnen','to describe; to designate',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('sich verlassen auf (+ Akk.)','to rely on',NULL,'verließ','hat verlassen',NULL,1);
INSERT INTO vocab VALUES('verstehen unter (+ Dat.)','to understand by; to mean by',NULL,'verstand','hat verstanden',NULL,1);
INSERT INTO vocab VALUES('hin- und hergerissen sein','to be torn between two things',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('(sich) aus den Augen verlieren','to lose sight of each other/someone',NULL,'verlor','hat verloren',NULL,1);
INSERT INTO vocab VALUES('lose','loose; casual',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('einerseits – andererseits','on the one hand – on the other hand',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('entweder – oder','either – or',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('nicht nur – sondern auch','not only – but also',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('sowohl – als auch','both – and',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('weder – noch','neither – nor',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('zwar – aber','although/admittedly – but',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Auftrag','order; commission; assignment','der',NULL,NULL,'Aufträge',1);
INSERT INTO vocab VALUES('in Auftrag geben','to commission; to order',NULL,'gab','hat gegeben',NULL,1);
INSERT INTO vocab VALUES('Daten','data','die',NULL,NULL,'Daten',1);
INSERT INTO vocab VALUES('Daten auswerten','to evaluate/analyze data',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Daten erfassen','to collect/record data',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Erdbevölkerung','world population','die',NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Fakt','fact','der',NULL,NULL,'Fakten',1);
INSERT INTO vocab VALUES('Freundschaftsanfrage','friend request','die',NULL,NULL,'Freundschaftsanfragen',1);
INSERT INTO vocab VALUES('Nutzer','user','der',NULL,NULL,'Nutzer',1);
INSERT INTO vocab VALUES('Redensart','idiom; saying','die',NULL,NULL,'Redensarten',1);
INSERT INTO vocab VALUES('ermöglichen','to make possible; to enable',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('vernetzt sein','to be connected/networked',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('über sechs Ecken kennen','to know through six degrees of separation',NULL,'kannte','hat gekannt',NULL,1);
INSERT INTO vocab VALUES('mittlerweile','meanwhile; by now',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Ankündigung','announcement','die',NULL,NULL,'Ankündigungen',1);
INSERT INTO vocab VALUES('Eindruck','impression','der',NULL,NULL,'Eindrücke',1);
INSERT INTO vocab VALUES('den Eindruck haben','to have the impression',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Gesprächsrunde','discussion group; panel discussion','die',NULL,NULL,'Gesprächsrunden',1);
INSERT INTO vocab VALUES('Ratgeber','guidebook; advisor','der',NULL,NULL,'Ratgeber',1);
INSERT INTO vocab VALUES('Verwirrung','confusion','die',NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('auffallen','to stand out; to attract attention',NULL,'fiel auf','ist aufgefallen',NULL,1);
INSERT INTO vocab VALUES('feststellen','to determine; to notice',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('oberflächlich','superficial',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Bedürfnis','need','das',NULL,NULL,'Bedürfnisse',1);
INSERT INTO vocab VALUES('Beziehung','relationship','die',NULL,NULL,'Beziehungen',1);
INSERT INTO vocab VALUES('eine Beziehung haben','to be in a relationship',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Dankbarkeit','gratitude','die',NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Emotion','emotion','die',NULL,NULL,'Emotionen',1);
INSERT INTO vocab VALUES('Komiker','comedian','der',NULL,NULL,'Komiker',1);
INSERT INTO vocab VALUES('Lebensabschnitt','stage/period of life','der',NULL,NULL,'Lebensabschnitte',1);
INSERT INTO vocab VALUES('Lebensphase','phase of life','die',NULL,NULL,'Lebensphasen',1);
INSERT INTO vocab VALUES('Teenager','teenager','der',NULL,NULL,'Teenager',1);
INSERT INTO vocab VALUES('zusammenkommen mit','to get together with',NULL,'kam zusammen','ist zusammengekommen',NULL,1);
INSERT INTO vocab VALUES('befreundet sein mit','to be friends with',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Freundschaft schließen mit','to make friends with',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Altersunterschied','age difference','der',NULL,NULL,'Altersunterschiede',1);
INSERT INTO vocab VALUES('Einblick','insight; glimpse','der',NULL,NULL,'Einblicke',1);
INSERT INTO vocab VALUES('Feedback','feedback','das',NULL,NULL,'Feedbacks',1);
INSERT INTO vocab VALUES('Folie','slide; transparency','die',NULL,NULL,'Folien',1);
INSERT INTO vocab VALUES('Inhaltsverzeichnis','table of contents','das',NULL,NULL,'Inhaltsverzeichnisse',1);
INSERT INTO vocab VALUES('Konkurrent','competitor','der',NULL,NULL,'Konkurrenten',1);
INSERT INTO vocab VALUES('Übergang','transition; crossing','der',NULL,NULL,'Übergänge',1);
INSERT INTO vocab VALUES('erwähnen','to mention',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('abenteuerlustig','adventurous',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('außergewöhnlich','extraordinary; unusual',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('extrovertiert','extroverted',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('hilfsbereit','helpful',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('introvertiert','introverted',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('nachdenklich','thoughtful; reflective',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('risikofreudig','willing to take risks',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('rücksichtslos/-voll','inconsiderate/considerate',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Auswertung','evaluation; analysis','die',NULL,NULL,'Auswertungen',1);
INSERT INTO vocab VALUES('Rückseite','back side; reverse','die',NULL,NULL,'Rückseiten',1);
INSERT INTO vocab VALUES('Vorderseite','front side','die',NULL,NULL,'Vorderseiten',1);
INSERT INTO vocab VALUES('bewerten','to evaluate; to assess',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('gestalten','to design; to shape',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Kontakte pflegen','to maintain contacts',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Besen','broom','der',NULL,NULL,'Besen',1);
INSERT INTO vocab VALUES('sorgen für','to take care of; to ensure',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('(sich) vertraut machen mit','to familiarize oneself/someone with',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('mental','mental',NULL,NULL,NULL,NULL,1);
INSERT INTO vocab VALUES('Profil','profile','das',NULL,NULL,'Profile',2);
INSERT INTO vocab VALUES('Anforderung','requirement','die',NULL,NULL,'Anforderungen',2);
INSERT INTO vocab VALUES('Bereich','area; field; department','der',NULL,NULL,'Bereiche',2);
INSERT INTO vocab VALUES('Bundesgebiet','federal territory; national territory','das',NULL,NULL,'Bundesgebiete',2);
INSERT INTO vocab VALUES('Klinik','clinic; hospital','die',NULL,NULL,'Kliniken',2);
INSERT INTO vocab VALUES('Konzept','concept','das',NULL,NULL,'Konzepte',2);
INSERT INTO vocab VALUES('Messe','trade fair; exhibition','die',NULL,NULL,'Messen',2);
INSERT INTO vocab VALUES('Schicht','shift; layer','die',NULL,NULL,'Schichten',2);
INSERT INTO vocab VALUES('Schichtdienst','shift work','der',NULL,NULL,'Schichtdienste',2);
INSERT INTO vocab VALUES('Spontaneität','spontaneity','die',NULL,NULL,'Spontaneitäten',2);
INSERT INTO vocab VALUES('Unternehmen','company; enterprise','das',NULL,NULL,'Unternehmen',2);
INSERT INTO vocab VALUES('Visitenkarte','business card','die',NULL,NULL,'Visitenkarten',2);
INSERT INTO vocab VALUES('Vorlesung','lecture','die',NULL,NULL,'Vorlesungen',2);
INSERT INTO vocab VALUES('erläutern','to explain',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('forschen','to research',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('knüpfen','to establish; to tie',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('Kontakte knüpfen','to establish contacts',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('mobil sein','to be mobile',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('ins Stocken geraten','to falter; to come to a halt',NULL,'geriet','ist geraten',NULL,2);
INSERT INTO vocab VALUES('tätig sein','to be active/working',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('zur Verfügung haben','to have at one’s disposal',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('Ablage','filing tray; storage; filing','die',NULL,NULL,'Ablagen',2);
INSERT INTO vocab VALUES('Assistent','assistant','der',NULL,NULL,'Assistenten',2);
INSERT INTO vocab VALUES('Bereichsleiter','department/section manager','der',NULL,NULL,'Bereichsleiter',2);
INSERT INTO vocab VALUES('Konferenz','conference','die',NULL,NULL,'Konferenzen',2);
INSERT INTO vocab VALUES('Position','position','die',NULL,NULL,'Positionen',2);
INSERT INTO vocab VALUES('Projektleiter','project manager','der',NULL,NULL,'Projektleiter',2);
INSERT INTO vocab VALUES('Unterlage','document; material','die',NULL,NULL,'Unterlagen',2);
INSERT INTO vocab VALUES('(sich) durchsetzen','to assert oneself; to prevail',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('dominant','dominant',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('durchsetzungsstark','assertive',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('ehrgeizig','ambitious',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('strukturiert','structured',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('teamfähig','team-oriented; able to work in a team',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('unabhängig','independent',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('Arbeitskraft','worker; labor force','die',NULL,NULL,'Arbeitskräfte',2);
INSERT INTO vocab VALUES('Effekt','effect','der',NULL,NULL,'Effekte',2);
INSERT INTO vocab VALUES('Motivation','motivation','die',NULL,NULL,'Motivationen',2);
INSERT INTO vocab VALUES('Reportage','report; documentary report','die',NULL,NULL,'Reportagen',2);
INSERT INTO vocab VALUES('Therapeut','therapist','der',NULL,NULL,'Therapeuten',2);
INSERT INTO vocab VALUES('Veränderung','change','die',NULL,NULL,'Veränderungen',2);
INSERT INTO vocab VALUES('Zusammenbruch','collapse; breakdown','der',NULL,NULL,'Zusammenbrüche',2);
INSERT INTO vocab VALUES('stammen von','to come/originate from',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('spüren','to feel; to sense',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('erfahren sein (in) (+ Dat.)','to be experienced in',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('begeistert','enthusiastic',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('Persönlichkeit','personality','die',NULL,NULL,'Persönlichkeiten',2);
INSERT INTO vocab VALUES('Steigerung','increase; rise','die',NULL,NULL,'Steigerungen',2);
INSERT INTO vocab VALUES('Umsatz','turnover; revenue; sales','der',NULL,NULL,'Umsätze',2);
INSERT INTO vocab VALUES('Werbeaktion','advertising campaign; promotion','die',NULL,NULL,'Werbeaktionen',2);
INSERT INTO vocab VALUES('erfüllen','to fulfill',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('hinterlassen','to leave behind',NULL,'hinterließ','hat hinterlassen',NULL,2);
INSERT INTO vocab VALUES('sich spezialisieren auf (+ Akk.)','to specialize in',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('verdreifachen','to triple',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('am Laufen halten','to keep running/going',NULL,'hielt','hat gehalten',NULL,2);
INSERT INTO vocab VALUES('kreativ','creative',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('ungezwungen','informal; relaxed',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('unkonventionell','unconventional',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('Gewissen','conscience','das',NULL,NULL,'Gewissen',2);
INSERT INTO vocab VALUES('Offenheit','openness','die',NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('Stichwort','keyword; cue','das',NULL,NULL,'Stichwörter',2);
INSERT INTO vocab VALUES('pendeln','to commute',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('Bezug nehmen auf','to refer to',NULL,'nahm','hat genommen',NULL,2);
INSERT INTO vocab VALUES('ein Gespräch führen','to have/conduct a conversation',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('sich die Zeit vertreiben','to pass the time',NULL,'vertrieb','hat vertrieben',NULL,2);
INSERT INTO vocab VALUES('flüssig','fluent; liquid',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('aufgrund','because of; due to',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('ausführlich','detailed; in detail',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('dank','thanks to',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('zumindest','at least',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('Arbeitsgericht','labor court','das',NULL,NULL,'Arbeitsgerichte',2);
INSERT INTO vocab VALUES('Arbeitsrechtler','labor-law specialist','der',NULL,NULL,'Arbeitsrechtler',2);
INSERT INTO vocab VALUES('Aufregung','excitement; agitation','die',NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('Aufsehen','sensation; stir','das',NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('Aufsehen erregen','to cause a stir; to attract attention',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('Besprechung','meeting; discussion','die',NULL,NULL,'Besprechungen',2);
INSERT INTO vocab VALUES('Diebstahl','theft','der',NULL,NULL,'Diebstähle',2);
INSERT INTO vocab VALUES('Einverständnis','consent; agreement','das',NULL,NULL,'Einverständnisse',2);
INSERT INTO vocab VALUES('Fachanwalt','specialist lawyer','der',NULL,NULL,'Fachanwälte',2);
INSERT INTO vocab VALUES('Genehmigung','approval; permission','die',NULL,NULL,'Genehmigungen',2);
INSERT INTO vocab VALUES('Keks','cookie; biscuit','der',NULL,NULL,'Kekse',2);
INSERT INTO vocab VALUES('Sitte','custom','die',NULL,NULL,'Sitten',2);
INSERT INTO vocab VALUES('aufladen','to charge; to load',NULL,'lud auf','hat aufgeladen',NULL,2);
INSERT INTO vocab VALUES('sich befassen mit','to deal with; to concern oneself with',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('erwähnen','to mention',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('naschen','to snack; to nibble sweets',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('Bedenken äußern','to express concerns',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('den Job kosten','to cost someone their job',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('ausdrücklich','explicit; express',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('bedenklich','questionable; worrying',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('fristlos','without notice; immediate',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('(un)üblich','(un)usual',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('eine Reihe von','a number of; a series of',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('Konvention','convention','die',NULL,NULL,'Konventionen',2);
INSERT INTO vocab VALUES('Anliegen','concern; request','das',NULL,NULL,'Anliegen',2);
INSERT INTO vocab VALUES('weswegen','which is why; because of which',NULL,NULL,NULL,NULL,2);
INSERT INTO vocab VALUES('Medium','medium; media outlet','das',NULL,NULL,'Medien',3);
INSERT INTO vocab VALUES('Nutzung','use; usage','die',NULL,NULL,'Nutzungen',3);
INSERT INTO vocab VALUES('benutzen','to use',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('nutzen','to use; to utilize',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('Buchhändlerin','bookseller','die',NULL,NULL,'Buchhändlerinnen',3);
INSERT INTO vocab VALUES('Lesung','reading','die',NULL,NULL,'Lesungen',3);
INSERT INTO vocab VALUES('Neuheit','novelty; new release','die',NULL,NULL,'Neuheiten',3);
INSERT INTO vocab VALUES('Sachbuch','non-fiction book','das',NULL,NULL,'Sachbücher',3);
INSERT INTO vocab VALUES('Stammkunde','regular customer','der',NULL,NULL,'Stammkunden',3);
INSERT INTO vocab VALUES('animieren zu','to encourage/motivate to',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('beurteilen','to judge; to assess',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('quatschen','to chat',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('angenommen werden','to be accepted/adopted',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('verführerisch','tempting; seductive',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('Aufnahme','recording; photo; admission','die',NULL,NULL,'Aufnahmen',3);
INSERT INTO vocab VALUES('Luftaufnahme','aerial photograph','die',NULL,NULL,'Luftaufnahmen',3);
INSERT INTO vocab VALUES('Bildband','illustrated book; photo book','der',NULL,NULL,'Bildbände',3);
INSERT INTO vocab VALUES('Leseratte','bookworm','die',NULL,NULL,'Leseratten',3);
INSERT INTO vocab VALUES('anrühren','to touch; to stir',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('greifen zu','to reach for; to grab',NULL,'griff zu','hat zugegriffen',NULL,3);
INSERT INTO vocab VALUES('jedermanns Sache sein','to be everyone’s cup of tea',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('Auflage','edition; print run','die',NULL,NULL,'Auflagen',3);
INSERT INTO vocab VALUES('Befürchtung','fear; concern','die',NULL,NULL,'Befürchtungen',3);
INSERT INTO vocab VALUES('Branche','sector; industry','die',NULL,NULL,'Branchen',3);
INSERT INTO vocab VALUES('Geschehen','events; happenings','das',NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('Gleichaltrige','person of the same age; peer','die/der',NULL,NULL,'Gleichaltrigen',3);
INSERT INTO vocab VALUES('Heranwachsende','adolescent; young person growing up','die/der',NULL,NULL,'Heranwachsenden',3);
INSERT INTO vocab VALUES('Nachrichtenmagazin','news magazine','das',NULL,NULL,'Nachrichtenmagazine',3);
INSERT INTO vocab VALUES('Popularität','popularity','die',NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('Printmedium','print medium','das',NULL,NULL,'Printmedien',3);
INSERT INTO vocab VALUES('Vorbild','role model; example','das',NULL,NULL,'Vorbilder',3);
INSERT INTO vocab VALUES('imitieren','to imitate',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('hierzulande','in this country',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('Dokumentarfilm','documentary film','der',NULL,NULL,'Dokumentarfilme',3);
INSERT INTO vocab VALUES('Drehbuch','screenplay; script','das',NULL,NULL,'Drehbücher',3);
INSERT INTO vocab VALUES('Drehort','filming location','der',NULL,NULL,'Drehorte',3);
INSERT INTO vocab VALUES('Hintergrund','background','der',NULL,NULL,'Hintergründe',3);
INSERT INTO vocab VALUES('Horrorfilm','horror film','der',NULL,NULL,'Horrorfilme',3);
INSERT INTO vocab VALUES('Komödie','comedy','die',NULL,NULL,'Komödien',3);
INSERT INTO vocab VALUES('Literaturverfilmung','film adaptation of literature','die',NULL,NULL,'Literaturverfilmungen',3);
INSERT INTO vocab VALUES('Maskenbildner','makeup artist','der',NULL,NULL,'Maskenbildner',3);
INSERT INTO vocab VALUES('Prominente','celebrity','die/der',NULL,NULL,'Prominenten',3);
INSERT INTO vocab VALUES('Redakteur','editor','der',NULL,NULL,'Redakteure',3);
INSERT INTO vocab VALUES('Regisseur','director','der',NULL,NULL,'Regisseure',3);
INSERT INTO vocab VALUES('Skript','script','das',NULL,NULL,'Skripts/Skripte',3);
INSERT INTO vocab VALUES('Stylist','stylist','der',NULL,NULL,'Stylisten',3);
INSERT INTO vocab VALUES('Szene','scene','die',NULL,NULL,'Szenen',3);
INSERT INTO vocab VALUES('Vorlage','template; model; source material','die',NULL,NULL,'Vorlagen',3);
INSERT INTO vocab VALUES('führen','to lead; to conduct',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('ein Interview / Regie führen','to conduct an interview / direct',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('überarbeiten','to revise; to rework',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('umschreiben','to rewrite',NULL,'schrieb um','hat umgeschrieben',NULL,3);
INSERT INTO vocab VALUES('eine Buchvorlage umschreiben','to adapt/rewrite a book source',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('auswendig lernen','to learn by heart',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('einen Film drehen','to shoot/make a film',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('abwechslungsreich','varied; diverse',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('authentisch','authentic',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('bilderreich','rich in images',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('gruselig','creepy; scary',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('handlungsarm','low in plot/action',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('humorvoll','humorous',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('lehrreich','educational; instructive',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('reißerisch','sensationalist',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('(un)sachlich','(un)objective',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('turbulent','turbulent; lively',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('unterhaltsam','entertaining',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('witzig','funny',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('Raute','hash sign; diamond shape','die',NULL,NULL,'Rauten',3);
INSERT INTO vocab VALUES('Großleinwand','big screen','die',NULL,NULL,'Großleinwände',3);
INSERT INTO vocab VALUES('Schwäche','weakness','die',NULL,NULL,'Schwächen',3);
INSERT INTO vocab VALUES('sich abheben von','to stand out from',NULL,'hob ab','hat abgehoben',NULL,3);
INSERT INTO vocab VALUES('anschaffen','to acquire; to buy',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('dahinterstecken','to be behind it',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('starren','to stare',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('verfolgen','to follow; to pursue',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('bemerkenswert','remarkable',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('großartig','great; magnificent',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('Komplexität','complexity','die',NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('Logik','logic','die',NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('Meldung','report; notification','die',NULL,NULL,'Meldungen',3);
INSERT INTO vocab VALUES('Quelle','source','die',NULL,NULL,'Quellen',3);
INSERT INTO vocab VALUES('erläutern','to explain',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('ansprechend','appealing',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('anspruchsvoll','demanding; sophisticated',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('bebildert','illustrated',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('übersichtlich','clear; well-organized',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('das Herz ausschütten','to pour one’s heart out',NULL,NULL,NULL,NULL,3);
INSERT INTO vocab VALUES('Bildungswerk','educational institution/organization','das',NULL,NULL,'Bildungswerke',4);
INSERT INTO vocab VALUES('Bundesfreiwilligendienst','federal voluntary service','der',NULL,NULL,'Bundesfreiwilligendienste',4);
INSERT INTO vocab VALUES('(Bundes)Freiwilligendienst leisten','to do federal/voluntary service',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('Einrichtung','institution; facility','die',NULL,NULL,'Einrichtungen',4);
INSERT INTO vocab VALUES('Behindertenwerkstatt','sheltered workshop for disabled people','die',NULL,NULL,'Behindertenwerkstätten',4);
INSERT INTO vocab VALUES('Beliebtheitsskala','popularity scale/ranking','die',NULL,NULL,'Beliebtheitsskalen',4);
INSERT INTO vocab VALUES('Dienstleistung','service','die',NULL,NULL,'Dienstleistungen',4);
INSERT INTO vocab VALUES('Einheimische','local; native resident','die/der',NULL,NULL,'Einheimischen',4);
INSERT INTO vocab VALUES('Faust','fist','die',NULL,NULL,'Fäuste',4);
INSERT INTO vocab VALUES('etwas auf eigene Faust unternehmen','to do something on one’s own initiative',NULL,'unternahm','hat unternommen',NULL,4);
INSERT INTO vocab VALUES('Gegenseitigkeit','reciprocity','die',NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('auf Gegenseitigkeit beruhen','to be based on reciprocity',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('Gelegenheitsjob','casual/temporary job','der',NULL,NULL,'Gelegenheitsjobs',4);
INSERT INTO vocab VALUES('Schulabgänger','school leaver','der',NULL,NULL,'Schulabgänger',4);
INSERT INTO vocab VALUES('Weise','way; manner','die',NULL,NULL,'Weisen',4);
INSERT INTO vocab VALUES('auf diese Weise','in this way',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('Zuschuss','grant; subsidy','der',NULL,NULL,'Zuschüsse',4);
INSERT INTO vocab VALUES('vorgehen','to proceed; to take action',NULL,'ging vor','ist vorgegangen',NULL,4);
INSERT INTO vocab VALUES('Kenntnisse anwenden','to apply knowledge',NULL,'wendete/wandte an','hat angewendet/angewandt',NULL,4);
INSERT INTO vocab VALUES('Wissen erwerben','to acquire knowledge',NULL,'erwarb','hat erworben',NULL,4);
INSERT INTO vocab VALUES('einheimisch','local; native',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('gegenüberliegend','opposite; facing',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('gemeinnützig','non-profit; charitable',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('ehe','before',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('in der Regel','as a rule; usually',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('sobald','as soon as',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('solange','as long as',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('Aufenthaltserlaubnis','residence permit','die',NULL,NULL,'Aufenthaltserlaubnisse',4);
INSERT INTO vocab VALUES('Auszeit','time out; break','die',NULL,NULL,'Auszeiten',4);
INSERT INTO vocab VALUES('Brückenjahr','gap year; bridging year','das',NULL,NULL,'Brückenjahre',4);
INSERT INTO vocab VALUES('begrenzen','to limit',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('durchatmen','to take a deep breath',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('sich etwas erfüllen','to fulfill something for oneself',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('sich leisten','to afford',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('sich wenden an (+ Akk.)','to turn/contact someone',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('berechtigt sein','to be entitled/authorized',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('jedem selbst überlassen sein','to be left up to each person',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('Bereicherung','enrichment','die',NULL,NULL,'Bereicherungen',4);
INSERT INTO vocab VALUES('Eintrag','entry','der',NULL,NULL,'Einträge',4);
INSERT INTO vocab VALUES('Mitbringsel','souvenir; small gift brought along','das',NULL,NULL,'Mitbringsel',4);
INSERT INTO vocab VALUES('beifügen','to attach; to enclose',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('bewerten','to evaluate; to assess',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('zugeben','to admit',NULL,'gab zu','hat zugegeben',NULL,4);
INSERT INTO vocab VALUES('eine Erfahrung nicht missen wollen','not to want to miss an experience',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('lohnend','worthwhile; rewarding',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('Berufsorientierung','career orientation','die',NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('Berufsorientierungsmesse','career-orientation fair','die',NULL,NULL,'Berufsorientierungsmessen',4);
INSERT INTO vocab VALUES('Notendurchschnitt','grade average','der',NULL,NULL,'Notendurchschnitte',4);
INSERT INTO vocab VALUES('Leistungsdruck','pressure to perform','der',NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('Vorliebe','preference','die',NULL,NULL,'Vorlieben',4);
INSERT INTO vocab VALUES('Werkstudent','working student','der',NULL,NULL,'Werkstudenten',4);
INSERT INTO vocab VALUES('jemandem absagen','to cancel on/refuse someone',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('jemandem zusagen','to appeal to someone; to accept',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('geeignet sein für','to be suitable for',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('infrage kommen für','to be an option for',NULL,'kam','ist gekommen',NULL,4);
INSERT INTO vocab VALUES('ausnahmsweise','exceptionally; as an exception',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('dummerweise','stupidly; unfortunately',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('erfreulicherweise','fortunately; pleasingly',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('erstaunlicherweise','surprisingly',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('probeweise','on a trial basis',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('sinnvollerweise','sensibly; appropriately',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('stellenweise','in places; at some points',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('überraschenderweise','surprisingly',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('vergleichsweise','comparatively',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('verständlicherweise','understandably',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('Aufnahmeprüfung','entrance exam/audition','die',NULL,NULL,'Aufnahmeprüfungen',4);
INSERT INTO vocab VALUES('Bühnenbild','stage design; set','das',NULL,NULL,'Bühnenbilder',4);
INSERT INTO vocab VALUES('Klassiker','classic','der',NULL,NULL,'Klassiker',4);
INSERT INTO vocab VALUES('Niederlage','defeat','die',NULL,NULL,'Niederlagen',4);
INSERT INTO vocab VALUES('Spielplan','schedule; program','der',NULL,NULL,'Spielpläne',4);
INSERT INTO vocab VALUES('Studiengang','degree program','der',NULL,NULL,'Studiengänge',4);
INSERT INTO vocab VALUES('aufführen','to perform; to stage',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('vielfältig','diverse; varied',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('zeitgenössisch','contemporary',NULL,NULL,NULL,NULL,4);
INSERT INTO vocab VALUES('Fotomontage','photomontage','die',NULL,NULL,'Fotomontagen',5);
INSERT INTO vocab VALUES('Hilfsmittel','aid; tool','das',NULL,NULL,'Hilfsmittel',5);
INSERT INTO vocab VALUES('Kampagne','campaign','die',NULL,NULL,'Kampagnen',5);
INSERT INTO vocab VALUES('Styling','styling','das',NULL,NULL,'Stylings',5);
INSERT INTO vocab VALUES('wirken','to seem; to have an effect',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('Ausgabe','issue; edition; output','die',NULL,NULL,'Ausgaben',5);
INSERT INTO vocab VALUES('Ausschreibung','announcement; call for applications/tenders','die',NULL,NULL,'Ausschreibungen',5);
INSERT INTO vocab VALUES('Aspekt','aspect','der',NULL,NULL,'Aspekte',5);
INSERT INTO vocab VALUES('Klamotten','clothes','die',NULL,NULL,'Klamotten',5);
INSERT INTO vocab VALUES('Laufsteg','catwalk; runway','der',NULL,NULL,'Laufstege',5);
INSERT INTO vocab VALUES('Makel','flaw; blemish','der',NULL,NULL,'Makel',5);
INSERT INTO vocab VALUES('Model','model','das',NULL,NULL,'Models',5);
INSERT INTO vocab VALUES('Wettbewerb','competition','der',NULL,NULL,'Wettbewerbe',5);
INSERT INTO vocab VALUES('sich beschränken auf (+ Akk.)','to limit/restrict oneself to',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('durchblättern','to leaf through',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('irritieren','to irritate; to confuse',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('sein lassen','to leave it; to stop doing it',NULL,'ließ sein','hat sein gelassen',NULL,5);
INSERT INTO vocab VALUES('staunen über (+ Akk.)','to be amazed at',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('stylen','to style',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('vorführen','to present; to demonstrate; to model',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('vorschreiben','to prescribe; to dictate',NULL,'schrieb vor','hat vorgeschrieben',NULL,5);
INSERT INTO vocab VALUES('verzichten auf (+ Akk.)','to do without; to refrain from',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('zustimmen','to agree',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('attraktiv','attractive',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('selbstbewusst','self-confident',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('vielseitig','versatile',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('Entdeckung','discovery','die',NULL,NULL,'Entdeckungen',5);
INSERT INTO vocab VALUES('Mentalität','mentality','die',NULL,NULL,'Mentalitäten',5);
INSERT INTO vocab VALUES('Schönheitsideal','ideal of beauty','das',NULL,NULL,'Schönheitsideale',5);
INSERT INTO vocab VALUES('prägen','to shape; to influence',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('entdeckt werden','to be discovered',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('neidisch sein','to be jealous/envious',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('riskant sein','to be risky',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('stammen aus','to come from/originate from',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('souverän','confident; assured',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('Augenbraue','eyebrow','die',NULL,NULL,'Augenbrauen',5);
INSERT INTO vocab VALUES('Äußerlichkeit','external appearance; outward feature','die',NULL,NULL,'Äußerlichkeiten',5);
INSERT INTO vocab VALUES('Garderobe','wardrobe; cloakroom','die',NULL,NULL,'Garderoben',5);
INSERT INTO vocab VALUES('Körperbehaarung','body hair','die',NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('Kosmetikerin','beautician','die',NULL,NULL,'Kosmetikerinnen',5);
INSERT INTO vocab VALUES('Wimper','eyelash','die',NULL,NULL,'Wimpern',5);
INSERT INTO vocab VALUES('abraten von','to advise against',NULL,'riet ab','hat abgeraten',NULL,5);
INSERT INTO vocab VALUES('sich engagieren für (+ Akk.)','to get involved/commit oneself for',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('färben','to dye; to color',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('lackieren','to paint; to varnish; to polish',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('plädieren für (+ Akk.)','to plead/argue for',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('übertreiben','to exaggerate; to overdo',NULL,'übertrieb','hat übertrieben',NULL,5);
INSERT INTO vocab VALUES('effektiv','effective',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('Lücke','gap','die',NULL,NULL,'Lücken',5);
INSERT INTO vocab VALUES('kein Auge zutun','not to sleep a wink',NULL,'tat zu','hat zugetan',NULL,5);
INSERT INTO vocab VALUES('jemandem die Augen öffnen','to open someone’s eyes',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('beide Augen zudrücken','to turn a blind eye',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('auf eigenen Füßen stehen','to stand on one’s own two feet',NULL,'stand','hat gestanden',NULL,5);
INSERT INTO vocab VALUES('auf großem Fuß leben','to live extravagantly',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('kalte Füße bekommen','to get cold feet',NULL,'bekam','hat bekommen',NULL,5);
INSERT INTO vocab VALUES('etwas hängt einem zum Hals heraus','to be fed up with something',NULL,'hing','hat gehangen',NULL,5);
INSERT INTO vocab VALUES('jemandem um den Hals fallen','to throw one’s arms around someone',NULL,'fiel','ist gefallen',NULL,5);
INSERT INTO vocab VALUES('Hals über Kopf','head over heels; hastily',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('etwas in die Hand nehmen','to take something into one’s own hands',NULL,'nahm','hat genommen',NULL,5);
INSERT INTO vocab VALUES('zwei linke Hände haben','to be all thumbs',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('in festen Händen sein','to be in a committed relationship',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('den Kopf verlieren','to lose one’s head',NULL,'verlor','hat verloren',NULL,5);
INSERT INTO vocab VALUES('sich etwas durch den Kopf gehen lassen','to think something over',NULL,'ließ','hat gelassen',NULL,5);
INSERT INTO vocab VALUES('von Kopf bis Fuß','from head to toe',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('eine starke Schulter zum Anlehnen brauchen','to need a strong shoulder to lean on',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('etwas auf die leichte Schulter nehmen','to take something lightly',NULL,'nahm','hat genommen',NULL,5);
INSERT INTO vocab VALUES('Beweglichkeit','mobility; flexibility','die',NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('Fitness','fitness','die',NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('Gelenk','joint','das',NULL,NULL,'Gelenke',5);
INSERT INTO vocab VALUES('Gleichgewicht','balance','das',NULL,NULL,'Gleichgewichte',5);
INSERT INTO vocab VALUES('Haltung','posture; attitude','die',NULL,NULL,'Haltungen',5);
INSERT INTO vocab VALUES('Kondition','condition; stamina','die',NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('Koordination','coordination','die',NULL,NULL,'Koordinationen',5);
INSERT INTO vocab VALUES('Muskel','muscle','der',NULL,NULL,'Muskeln',5);
INSERT INTO vocab VALUES('berühren','to touch',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('kratzen','to scratch',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('kreisen','to circle; to rotate',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('rutschen','to slide; to slip',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('verschränken','to cross/fold',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('sich vorbeugen','to bend forward',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('jemandem liegt etwas (nicht)','something does (not) suit/appeal to someone',NULL,'lag','hat gelegen',NULL,5);
INSERT INTO vocab VALUES('gelenkig','flexible; supple',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('sanft','gentle; soft',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('etwas Ausgefallenes','something unusual/fancy',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('Inserent','advertiser','der',NULL,NULL,'Inserenten',5);
INSERT INTO vocab VALUES('Niveau','level; standard','das',NULL,NULL,'Niveaus',5);
INSERT INTO vocab VALUES('Choreographie','choreography','die',NULL,NULL,'Choreographien',5);
INSERT INTO vocab VALUES('ausprobieren','to try out',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('(herum)hüpfen','to hop/jump around',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('klatschen','to clap',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('schütteln','to shake',NULL,NULL,NULL,NULL,5);
INSERT INTO vocab VALUES('Galerie','gallery','die',NULL,NULL,'Galerien',6);
INSERT INTO vocab VALUES('kulinarisch','culinary',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('App','app','die',NULL,NULL,'Apps',6);
INSERT INTO vocab VALUES('Betrieb','operation; company/business','der',NULL,NULL,'Betriebe',6);
INSERT INTO vocab VALUES('in Betrieb sein','to be in operation',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('Funktionsweise','mode of operation; how something works','die',NULL,NULL,'Funktionsweisen',6);
INSERT INTO vocab VALUES('herausfiltern','to filter out',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('sich verfahren','to get lost while driving',NULL,'verfuhr sich','hat sich verfahren',NULL,6);
INSERT INTO vocab VALUES('vornehm','distinguished; elegant',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('Auslauf','run-out; end; outlet','der',NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('Kuppel','dome','die',NULL,NULL,'Kuppeln',6);
INSERT INTO vocab VALUES('Label','label','das',NULL,NULL,'Labels',6);
INSERT INTO vocab VALUES('Meisterwerk','masterpiece','das',NULL,NULL,'Meisterwerke',6);
INSERT INTO vocab VALUES('Prominenz','celebrities; prominence','die',NULL,NULL,'Prominenzen',6);
INSERT INTO vocab VALUES('Schwerpunkt','focus; main emphasis','der',NULL,NULL,'Schwerpunkte',6);
INSERT INTO vocab VALUES('Spektakel','spectacle','das',NULL,NULL,'Spektakel',6);
INSERT INTO vocab VALUES('Uhrwerk','clockwork mechanism','das',NULL,NULL,'Uhrwerke',6);
INSERT INTO vocab VALUES('sich blicken lassen','to show up; to make an appearance',NULL,'ließ','hat gelassen',NULL,6);
INSERT INTO vocab VALUES('flanieren','to stroll',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('vereinen','to unite; to combine',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('begeistert sein von','to be enthusiastic about',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('bekannt sein für','to be known for',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('beliebt sein bei','to be popular with',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('berühmt sein für','to be famous for',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('stolz sein auf (+ Akk.)','to be proud of',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('überrascht sein über (+ Akk.)','to be surprised about',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('zufrieden sein mit','to be satisfied with',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('charakteristisch','characteristic',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('einstig','former',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('legendär','legendary',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('lohnenswert','worthwhile',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('mittelalterlich','medieval',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('urban','urban',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('Infrastruktur','infrastructure','die',NULL,NULL,'Infrastrukturen',6);
INSERT INTO vocab VALUES('Spalte','column; gap','die',NULL,NULL,'Spalten',6);
INSERT INTO vocab VALUES('landeskundlich','related to regional/cultural studies',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('Ausflügler','day-tripper; excursionist','der',NULL,NULL,'Ausflügler',6);
INSERT INTO vocab VALUES('Fassade','facade','die',NULL,NULL,'Fassaden',6);
INSERT INTO vocab VALUES('Hauptverkehrsader','main traffic artery/route','die',NULL,NULL,'Hauptverkehrsadern',6);
INSERT INTO vocab VALUES('Stadtrand','outskirts; edge of town','der',NULL,NULL,'Stadtränder',6);
INSERT INTO vocab VALUES('Tagesstätte','daycare/day center','die',NULL,NULL,'Tagesstätten',6);
INSERT INTO vocab VALUES('Umweltministerium','environment ministry','das',NULL,NULL,'Umweltministerien',6);
INSERT INTO vocab VALUES('auffrischen','to refresh',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('(sich) austauschen','to exchange; to communicate',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('sanieren','to renovate; to restore',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('tauschen','to exchange; to swap',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('sich wandeln','to change; to transform',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('wimmeln von','to teem with; to be swarming with',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('eindrucksvoll','impressive',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('einspurig','single-lane',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('einzigartig','unique',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('gebürtig','native-born',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('gutbürgerlich','middle-class; traditional home-style',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('heruntergekommen','run-down',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('mehrspurig','multi-lane',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('Einkaufspassage','shopping arcade','die',NULL,NULL,'Einkaufspassagen',6);
INSERT INTO vocab VALUES('Imbissstand','snack stand','der',NULL,NULL,'Imbissstände',6);
INSERT INTO vocab VALUES('Nahverkehrssystem','local public transport system','das',NULL,NULL,'Nahverkehrssysteme',6);
INSERT INTO vocab VALUES('Stadttor','city gate','das',NULL,NULL,'Stadttore',6);
INSERT INTO vocab VALUES('Versorgung','supply; provision','die',NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('Verwaltungsgebiet','administrative district/area','das',NULL,NULL,'Verwaltungsgebiete',6);
INSERT INTO vocab VALUES('Wasserleitung','water pipe; water supply line','die',NULL,NULL,'Wasserleitungen',6);
INSERT INTO vocab VALUES('erschließen','to develop; to make accessible',NULL,'erschloss','hat erschlossen',NULL,6);
INSERT INTO vocab VALUES('versorgen','to supply; to provide for',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('voraussagen','to predict; to forecast',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('bedeckt sein (mit)','to be covered (with)',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('detailliert','detailed',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('entsprechend','corresponding; appropriate',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('schadhaft','damaged; defective',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('Bedenken','concerns; reservations','die',NULL,NULL,'Bedenken',6);
INSERT INTO vocab VALUES('Einigung','agreement','die',NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('sich einigen','to agree; to reach an agreement',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('entkräften','to refute; to invalidate',NULL,NULL,NULL,NULL,6);
INSERT INTO vocab VALUES('Einstellung','attitude; setting; hiring','die',NULL,NULL,'Einstellungen',6);
INSERT INTO vocab VALUES('Leidenschaft','passion','die',NULL,NULL,'Leidenschaften',6);
INSERT INTO vocab VALUES('Welle','wave','die',NULL,NULL,'Wellen',6);
COMMIT;
